/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package monorepo.utilities

import monorepo.list.LinkedList

class JoinUtils {
    companion object {
        fun join(source: LinkedList): String {
            return source.joinToString(" ")
        }
    }
}
